### ISSUE TITLE
move to specific slide or the last slide

### ISSUE THREAD

**Issue by Nightzer** [fionnachan/fSlider#1]
Nice work and an excellent slider. Ive been using your slider for quite some time but now i may need some new method to move to a specific slide or move to the last slide, any ideas?

**Comment by fionnachan** [comment]
Hello @Nightzer 
There is this function already, but I forgot to put on the documentation before.
Please try to use this function:

`$('.multi4Slider').fSlider('goToSlide', targetSlideIndex);` // targetSlideIndex [integer counted from 0]

**Comment by Nightzer** [comment]
Thx, just what i needed :+1:
